# Cesium 133
# B. Marcelis et al., PRB 70 012701 (2004)


m = 133 # mass in AMU
i = 3.5 # 7/2

g_S = 2.0023193043622
g_L = 0.99999369
g_I = -0.0009951414

a_s = 905 # background statteriing length in units of a_0 # Even this might want to be put into a structure like below in the future

T_Melt = 301.5 
T_Boil = 944

Vapor_A_Solid = 7.715 # 0.123 + 2.881 + 4.711
Vapor_A_Liquid = 7.169 # 0.123 + 2.881 + 4.165

Vapor_B_Solid = 3999
Vapor_B_Liquid = 3830

# States
[states]
    [states."6s_1/2"]
        l = 0.0
        s = 0.5 # 1/2
        j = 0.5 # 1/2

    [states."6p_1/2"]
        l = 1.0
        s = 0.5 # 1/2
        j = 0.5 # 1/2


    [states."6p_3/2"]
        l = 1.0
        s = 0.5 # 1/2
        j = 1.5 # 3/2

# Transitions for which we have data
[transitions]
    [transitions."6p_1/2->6s_1/2"]
        name = "D1"
        "τ" = 34.791e-9
        "λ" = 894.59295986e-9

    [transitions."6p_3/2->6s_1/2"]
        name = "D2"
        "τ" = 30.405e-9
        "λ" = 852.34727582e-9