m = 39.96399848 # mass in AMU
i = 4 # 9/2

g_S = 2.0023193043622
g_L = 0.99999369
g_I = -0.0009951414

a_s = 174 # background statteriing length in units of a_0 # Even this might want to be put into a structure like below in the future
c_6 = 4698

T_Melt = 336.8
T_Boil = 1047.15

Vapor_A_Solid = 7.9667
Vapor_A_Liquid = 7.4077

Vapor_B_Solid = 4646
Vapor_B_Liquid = 4453

# States
[states]
    [states."4s_1/2"]
        A = -285.7308e6
        g_J = 2.00233113

        l = 0.0
        s = 0.5 # 1/2
        j = 0.5 # 1/2

    [states."4p_1/2"]
        A = -34.523e6

        g_J = 0.666

        l = 1.0
        s = 0.5 # 1/2
        j = 0.5 # 1/2


    [states."4p_3/2"]
        A = -7.585e6
        B = -3.455e6

        g_J = 1.3362

        l = 1.0
        s = 0.5 # 1/2
        j = 1.5 # 3/2

# Transitions for which we have data
[transitions]

    [transitions."4p_1/2->4s_1/2"]
        name = "D1"
        "τ" = 26.37e-9
        "λ" = 770.108136507e-9

    [transitions."4p_3/2->4s_1/2"]
        name = "D2"
        "τ" = 26.37e-9
        "λ" = 766.700674872e-9