m = 22.9897692807 # mass in AMU
a_s = 63 # background statteriing length in units of a_0 # Even this might want to be put into a structure like below in the future
i = 1.5 # 3/2

T_Melt = 370.8
T_Boil = 1156

Vapor_A_Solid = 8.302 # 0.123 + 2.881 + 5.298
Vapor_A_Liquid = 7.708 # 0.123 + 2.881 + 4.704

Vapor_B_Solid = 5603
Vapor_B_Liquid = 5377

